# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-30 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_remove_award_ignoreanimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='changeWinRateInPlace',
            field=models.BooleanField(default=False, help_text='\u8bbe\u7f6e\u4e3atrue\u8868\u793a\u53ef\u4ee5\u4e34\u65f6\u8c03\u6574\u4eba\u6570\u8fdb\u884c\u4fee\u6539', verbose_name='\u662f\u5426\u53ef\u4ee5\u73b0\u573a\u66f4\u6539\u4e2d\u5956\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='award',
            name='everyoneCanDraw',
            field=models.BooleanField(default=False, help_text='\u8bbe\u7f6e\u4e3atrue\u8868\u793a\u8be5\u5956\u53ef\u4ee5\u8ddf\u5176\u4ed6\u5956\u9879\u91cd\u590d\u4e2d\u5956', verbose_name='\u662f\u5426\u6240\u6709\u4eba\u90fd\u53ef\u4ee5\u62bd\u5956'),
        ),
        migrations.AlterField(
            model_name='award',
            name='isAddToExclusion',
            field=models.BooleanField(default=False, help_text='\u8bbe\u7f6e\u4e3atrue\uff0c\u4e2d\u4e86\u8be5\u5956\u7684\u4eba\u5458\uff0c\u65e0\u6cd5\u518d\u53c2\u4e0e\u91cd\u590d\u62bd\u5956', verbose_name='\u4e2d\u5956\u4eba\u5458\u662f\u5426\u52a0\u5230\u6392\u9664\u540d\u5355'),
        ),
        migrations.AlterField(
            model_name='award',
            name='needInput',
            field=models.BooleanField(default=False, help_text='\u8bbe\u7f6e\u4e3atrue\u8868\u793a\u53ef\u4ee5\u4e0d\u5173\u95ed\u62bd\u5956\u9875\u9762\u4e0a\u8fde\u7eed\u62bd\u5956\u548c\u4fee\u6539\u5956\u54c1\u5185\u5bb9', verbose_name='\u662f\u5426\u73b0\u573a\u8f93\u5165\u5956\u54c1'),
        ),
        migrations.AlterField(
            model_name='award',
            name='takeInScene',
            field=models.BooleanField(default=False, help_text='\u73b0\u573a\u9886\u5956\u9700\u8981\u4eba\u5728\u73b0\u573a\uff0c\u4e0d\u5728\u73b0\u573a\u53ef\u4ee5\u91cd\u65b0\u62bd\u53d6', verbose_name='\u662f\u5426\u73b0\u573a\u9886\u5956'),
        ),
    ]
